In [2]:
import pandas as pd
import random
import sqlite3

# Sample values to randomize
symbols = [
    ("TATASTEEL-EQ", "INE081A01020", "3499"),
    ("PARAGMILK-EQ", "INE883N01014", "17130"),
    ("SBIN-EQ", "INE062A01020", "3045"),
    ("INFY-EQ", "INE009A01021", "4085"),
    ("RELIANCE-EQ", "INE002A01018", "2885"),
]

data = []

for _ in range(10000):
    symbol, isin, token = random.choice(symbols)
    quantity = random.randint(1, 10)
    avg_price = round(random.uniform(100, 1000), 2)
    ltp = round(avg_price * random.uniform(0.9, 1.3), 2)
    close = round(ltp * random.uniform(0.95, 1.05), 2)
    pnl = round((ltp - avg_price) * quantity, 2)
    pnl_pct = round(((ltp - avg_price) / avg_price) * 100, 2)

    row = {
        "tradingsymbol": symbol,
        "exchange": "NSE",
        "isin": isin,
        "t1quantity": 0,
        "realisedquantity": quantity,
        "quantity": quantity,
        "authorisedquantity": 0,
        "product": "DELIVERY",
        "collateralquantity": None,
        "collateraltype": None,
        "haircut": 0,
        "averageprice": avg_price,
        "ltp": ltp,
        "symboltoken": token,
        "close": close,
        "profitandloss": pnl,
        "pnlpercentage": pnl_pct
    }

    data.append(row)

# Convert to DataFrame
df = pd.DataFrame(data)

# Connect to SQLite database (creates one if it doesn't exist)
conn = sqlite3.connect("holdings_data.db")

# Store the data into a table named 'holdings'
df.to_sql("holdings", conn, if_exists="replace", index=False)

# Close the connection
conn.close()

print("✅ Generated 10,000 rows and stored in SQLite database 'holdings_data.db'")

✅ Generated 10,000 rows and stored in SQLite database 'holdings_data.db'

In [3]:
df

,tradingsymbol,exchange,isin,t1quantity,realisedquantity,quantity,authorisedquantity,product,collateralquantity,collateraltype,haircut,averageprice,ltp,symboltoken,close,profitandloss,pnlpercentage
0,SBIN-EQ,NSE,INE062A01020,0,10,10,0,DELIVERY,None,None,0,852.99,1037.80,3045,1080.52,1848.10,21.67
1,SBIN-EQ,NSE,INE062A01020,0,10,10,0,DELIVERY,None,None,0,252.56,287.12,3045,277.23,345.60,13.68
2,INFY-EQ,NSE,INE009A01021,0,7,7,0,DELIVERY,None,None,0,248.87,229.57,4085,236.78,-135.10,-7.76
3,PARAGMILK-EQ,NSE,INE883N01014,0,1,1,0,DELIVERY,None,None,0,438.66,450.42,17130,461.58,11.76,2.68
4,RELIANCE-EQ,NSE,INE002A01018,0,1,1,0,DELIVERY,None,None,0,745.09,857.98,2885,883.80,112.89,15.15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,INFY-EQ,NSE,INE009A01021,0,3,3,0,DELIVERY,None,None,0,531.92,513.21,4085,506.94,-56.13,-3.52
9996,TATASTEEL-EQ,NSE,INE081A01020,0,10,10,0,DELIVERY,None,None,0,699.65,685.53,3499,714.57,-141.20,-2.02
9997,SBIN-EQ,NSE,INE062A01020,0,3,3,0,DELIVERY,None,None,0,160.09,194.87,3045,202.63,104.34,21.73
9998,RELIANCE-EQ,NSE,INE002A01018,0,10,10,0,DELIVERY,None,None,0,337.59,412.71,2885,426.47,751.20,22.25
9999,TATASTEEL-EQ,NSE,INE081A01020,0,8,8,0,DELIVERY,None,None,0,200.08,215.51,3499,220.07,123.44,7.71